
services:
  web:
    build: ./app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - .:/app
    
    networks:
      - graphql-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - graphql-network
  
  frontend:
    build: ./react-graphql-app
    command: "npm run dev -- --host"
    ports:
      - "3000:5173"
    volumes:
      - ./react-graphql-app:/app

    depends_on:
      - web
    networks:
      - graphql-network

volumes:
  pgdata:

networks:
  graphql-network:
    driver: bridge
